proyecto/cms/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.index),
	path('imagen', views.imagen),
	path ('loggedIn', views.loggedIn),
	path('logout', views.logout_view),
	# hay que poner ésta la última porque si no
	# nunca saldrían las anteriores
	path('<str:llave>', views.get_content),
]

proyecto/proyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView as login

urlpatterns = [
    path('cms/', include('cms.urls')),
    ##path('calc/', include('calc.urls')),
    path('admin/', admin.site.urls),
    path('login', login.as_view()),
]

proyecto/cms/models.py
from django.db import models

# Create your models here.

class Contenido(models.Model):
    clave = models.CharField(max_length=64)
    valor = models.TextField()

class Comentario(models.Model):
    contenido = models.ForeignKey(Contenido, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=200)
    cuerpo = models.TextField(blank=False)
    fecha = models.DateTimeField('publicado')

proyecto/cms/views.py
from django.shortcuts import render

from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt

from django.shortcuts import get_object_or_404
from .models import Contenido, Comentario

from django.contrib.auth import logout
from django.shortcuts import redirect

from django.template import loader

from django.utils import timezone

# Create your views here.

def index(request):
    content_list = Contenido.objects.all()
    context = {'content_list': content_list}
    return render(request, 'cms/homepage.html', context)


@csrf_exempt
def get_content(request, llave):
    if request.user.is_authenticated:
        if request.method == "PUT":
            valor = request.body.decode('utf-8')
        elif request.method == "POST":
            action = request.POST['action']
            if action == "Enviar Contenido":
                valor = request.POST['valor']
        if request.method == "PUT" or (request.method == "POST" and action == "Enviar Contenido"):
            try:
                c = Contenido.objects.get(clave=llave)
                c.valor = valor
            except Contenido.DoesNotExist:
                c = Contenido(clave=llave, valor=valor)
            c.save()
        if request.method == "POST" and action == "Enviar Comentario":
                c = Contenido.objects.get(clave=llave)
                titulo = request.POST['titulo']
                cuerpo = request.POST['cuerpo']
                q = Comentario(contenido=c, titulo=titulo, cuerpo=cuerpo, fecha=timezone.now())
                q.save()
        #formulario para usuarios autenticados
        contenido = get_object_or_404(Contenido, clave=llave)
        context = {'contenido': contenido}
        return render(request, 'cms/contenido_autenticado.html', context)
    else:
        #formulario para usuarios no autenticados
        contenido = get_object_or_404(Contenido, clave=llave)
        context = {'contenido': contenido}
        return render(request, 'cms/contenido_no_autenticado.html', context)

def loggedIn(request):
    if request.user.is_authenticated:
        logged = "Logged in as " + request.user.username + "<a href='/cms/logout'>Logout</a>"
    else:
        logged = "Not logged in. <a href='/admin/'>Login via admin</a>"
    return HttpResponse(logged)

def logout_view(request):
    logout(request)
    return redirect("/cms/")


def imagen(request):
    template = loader.get_template('cms/plantilla.html')
    context = {}
    return HttpResponse(template.render(context, request))

proyecto/cms/templates/cms/contenido_autenticado.html
<h1>{{ contenido.valor }}</h1>
    {% for comentario in contenido.comentario_set.all %}
        	{{ comentario.titulo }}  :
            {{ comentario.cuerpo }}<br>
            Date: {{ comentario.fecha }}<br>
    {% endfor %}

</br>

<form action="" method="POST">
Introduce un nuevo comentario para esta página:
<br>Título: <input type="text" name="titulo">
<br>Cuerpo: <input type="text" name="cuerpo">
<input type="submit" name="action" value="Enviar Comentario">
</form>

<br>

<form action="" method="POST">
  Introduce el (nuevo) contenido para esta página:
  <input type="text" name="valor">
  <input type="submit" name="action" value="Enviar Contenido">
</form>

proyecto/cms/templates/cms/contenido_no_autenticado.html
<h1>{{ contenido.valor }}</h1>
    {% for comentario in contenido.comentario_set.all %}
        	{{ comentario.titulo }}   :   
            {{ comentario.cuerpo }}<br>
            Date: {{ comentario.fecha }}<br>
    {% endfor %}
		</br>

proyecto/cms/templates/cms/homepage.html
{% if content_list %}
        <ul>
        {% for content in content_list %}
            <li><a href="/cms/{{ content.clave }}">{{ content.clave }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No contents are available.</p>
    {% endif %}

proyecto/proyecto/templates/cms/plantilla.html
{% load static %}
<img src="{% static "cms/example.jpg" %}" alt="My image">